version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout
     # start proprietary DB using private Docker image
     # with credentials stored in the UI
     - run: |
         echo "$DOCKER_PASS" | docker login quay.io --username $DOCKER_USER --password-stdin
         
     - run: git clone https://github.com/cerebrotech/platform-apps.git
     - run: pwd
     - run: ls -l
     - run: |
         chmod +x twistcli
         sudo cp twistcli /usr/local/bin