version: 2.1
jobs: 
  build:
   machine:
     image: ubuntu-1604:202004-01
   steps:
     - checkout
     # start proprietary DB using private Docker image
     # with credentials stored in the UI
     - run:
         name: Update the OS and Install all the dependencies
         command: |
          sudo apt-get update
          sudo apt-get install build-essential
          sudo apt-get install jq
          npm install yaml
          npm install jsonpath
          npm i convert-csv-to-array -S   
          npm install better-sqlite3  

     - run: |
         echo "$DOCKER_PASS" | docker login quay.io --username $DOCKER_USER --password-stdin
         
     - run: git clone https://github.com/cerebrotech/platform-apps.git
     - run: pwd
     - run: ls -l
     - run: |
         chmod +x twistcli
         sudo cp twistcli /usr/local/bin
         node -v
     - run: docker pull quay.io/domino/filetask-scripts:v0.1.5
     - run: twistcli images scan --user ${TW_UNAME} --password ${TW_PWD} --address ${COMPUTE_CONSOLE} --output-file results.json --publish --details quay.io/domino/filetask-scripts:v0.1.5

workflows:
    version: 2.1
    build_the_pipeline:
      jobs:
        - build

              

