version: 2.1
orbs:
  path-filtering: circleci/path-filtering@0.0.3
  
commands: 
  run-when-package-changed:
    description: Skip scan if not changes in requirement.txt
    parameters:
        pattern:
          type: string
    steps:
      - run:
          command: |
               if [[ "$CIRCLE_BRANCH" = "circleci-project-setup" ]] && (git diff --name-only --diff-filter=ADMR @~..@ | grep -Eq "<< parameters.pattern >>"); then
               echo "<< parameters.pattern >>"
               snyk test --file="<< parameters.pattern >>" --command=python3 || true
               fi  
          name: Run Snyk                              
jobs:
  build:
    docker:
      - image: cimg/node:14.10.1 # the primary container, where your job's commands are run
        
    steps:
      - checkout 
      - run:
          name: "Update Node.js and npm"
          command: |
            curl -sSL "https://nodejs.org/dist/v11.10.0/node-v11.10.0-linux-x64.tar.xz" | sudo tar --strip-components=2 -xJ -C /usr/local/bin/ node-v11.10.0-linux-x64/bin/node
            curl https://www.npmjs.com/install.sh | sudo bash
            
      - run: sudo apt-get update
      
      - run:
           name: Installing Python PIP
           command: sudo apt install python3-pip
      
      - run:
           name: Install Snyk CLI
           command: sudo npm install -g snyk
      - run:
           name: Authorizing with Snyk Server
           command: snyk config set api=8e5c3f81-e599-4caa-8fab-085a90fdf5dd

      - run:
           name: Installing Requirements 
           command: pip install -r requirements.txt 
      - run-when-package-changed:
          pattern: "requirements.txt"                          
           
