version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout
     # start proprietary DB using private Docker image
     # with credentials stored in the UI
     - run: |
         echo "$DOCKER_PASS" | docker login quay.io --username $DOCKER_USER --password-stdin
         
     - run: git clone https://github.com/cerebrotech/platform-apps.git
     - run: pwd
     - run: ls -l
     - run: |
         chmod +x twistcli
         sudo cp twistcli /usr/local/bin
     - run: docker pull quay.io/domino/filetask-scripts:v0.1.5
     - run: twistcli images scan --user ${TW_UNAME} --password ${TW_PWD} --address ${COMPUTE_CONSOLE} --output-file results.json --publish --details quay.io/domino/filetask-scripts:v0.1.5
     - run:
          name: "Update Node.js and npm"
          command: |
            curl -sSL "https://nodejs.org/dist/v11.10.0/node-v11.10.0-linux-x64.tar.xz" | sudo tar --strip-components=2 -xJ -C /usr/local/bin/ node-v11.10.0-linux-x64/bin/node
            curl https://www.npmjs.com/install.sh | sudo bash
     -  run: |
          npm install yaml
          npm install jsonpath
          npm i convert-csv-to-array -S
          npm install better-sqlite3 -S
     